name: Treinamento Behave

on:
  push:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      selenium-grid:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2gb
        ports:
          - 4444:4444
          - 7900:7900
        
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
  
      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.7'
          
      - name: Instalar dependências
        run: |
          python3 -m venv .venv
          source ./.venv/bin/activate
          pip install -r requirements.txt
          
      - name: Executar testes
        run: |
          source ./.venv/bin/activate
          behavex

      - name: Publicar artefatos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-behavex
          path: output/
          retention-days: 7
        
